### ISSUE TITLE
Sugestion for script

### ISSUE THREAD

**Issue by Bagaceiras** [mettalogic/arcanum-automation#2]
Before the recent update you could put an auto clicker on the player tab rest button so stamina was always full. 

You coud include something similar on this script 
On the tc_start_timers add a new timer example
  tc_timer_rest = window.setInterval(function() {
		if (tc_click_action("rest2"))
			for (let qs of document.querySelectorAll(".popup"))
				if (qs.children[0].children[0].innerHTML == "rest")
					qs.lastElementChild.children[1].lastElementChild.lastElementChild.click();
	}, 300);
This one runs every 300ms but you could make it optional with some UI setting plus textbox to enter time

Then on init add 
var tc_load_timer = window.setInterval(function() { 
....

window.clearInterval(tc_load_timer);

    tc_settab('player');
    tc_timer_init = window.setInterval(function() {
         debugger;
        for (let qs of document.querySelectorAll(".player-tables .action-btn:not(.locked)")) {
            var key = qs.lastChild.innerHTML.toLowerCase() + "2";
            if (!tc_actions.get(key)) {
                tc_actions.set(key, qs.firstChild);
                if (tc_debug) console.log("Action stored: " + qs.innerHTML);
            }
        }
        tc_start_timers();
        window.clearInterval(tc_timer_init);
    }, 2000);

This just goes to the player tab and adds the rest button to the actions naming it rest2

**Comment by mettalogic** [comment]
I tried that (spam rest on Player tab) a couple of times, but it seemed rather OP. It was reported and lemur fixed it by changing the UI. As such, I don't want to add that behaviour back in. There's obviously a fine line here, and auto-focus is another contender for being a bit OP, but until lemur changes the way that works, I'm happy to leave that in.

**Comment by Bagaceiras** [comment]
ok cool
